# Generated by Django 3.1 on 2025-06-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
