# Generated by Django 5.1 on 2025-06-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunnel", "0002_registrationtoken_is_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housetunnel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="registrationtoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
